/* eslint:disable */

// This file has been generated by https://github.com/reverbnation/protoc-gen-twirp_ts.
// Do not edit.

export interface IResult {
  title?: string
  
  toJSON?(): object
}

export interface IResultJSON {
  title?: string
  toJSON?(): object
}

export class Result implements IResult {
  private readonly _json: IResultJSON;

  constructor(m?: IResult) {
    this._json = {};
    if (m) {
      this._json['title'] = m.title;
    }
  }
  
  // title (title)
  public get title(): string {
    return this._json.title!
  }
  public set title(value: string) {
    this._json.title = value
  }
  
  static fromJSON(m: IResultJSON = {}): Result {
    return new Result({
      title: m['title']!
    })
  }

  public toJSON(): object {
    return this._json
  }
}